### ISSUE TITLE
Add Obtainable Secondary Points as a Header

### ISSUE THREAD

**Issue by MikeEmery** [maybe-hello-world/40k-roster-formatter#30]
I've seen lists where the secondary points the list gives up is printed at the top, and it makes pre-game discussions much quicker/easier.  Something like:
```
No prisioners: 9
Assasination: 6
Bring it down: 10
...
```

**Comment by maybe-hello-world** [comment]
Thanks for the suggestion!
I think I'll add it as an optional header that you can enable/disable.

**Comment by maybe-hello-world** [comment]
To be closed by #44

**Comment by maybe-hello-world** [comment]
Closed by #44
