### ISSUE TITLE
Abhor the Witch calculation on Dark Angels Ezekiel

### ISSUE THREAD

**Issue by smajchrz** [maybe-hello-world/40k-roster-formatter#51]
It seems that the calculation of Abhor the Witch secondary working incorrectly on Dark Angels Ezekiel as it returning 2 points instead 3.

> ABHOR THE WITCH
> End Game Objective
> 
> The presence of enemy psykers in this theatre of war can no longer be tolerated - hunt them down.
> You cannot select this secondary objective if your army includes any PSYKER units. Score 3 victory points at the end of the battle for each enemy PSYKER CHARACTER unit that is destroyed, and 2 victory points for every other enemy PSYKER unit that is destroyed.

> Ezekiel
> KEYWORDS: CHARACTER, INFANTRY, DEATHWING, INNER CIRCLE, PSYKER, LIBRARIAN, CHIEF LIBRARIAN, EZEKIEL

**Comment by smajchrz** [comment]
Can be closed. Seems to count it correctly on new DA lists.

**Comment by maybe-hello-world** [comment]
Closed by https://github.com/BSData/wh40k/pull/11678
