### ISSUE TITLE
No Prisoners Secondary Miscounting

### ISSUE THREAD

**Issue by Aekiel** [maybe-hello-world/40k-roster-formatter#56]
Every roster I upload miscalculates the value for No Prisoners, I think by including infantry characters in the calculation.

Here are a few examples of lists I've been uploading.

[Rosters.zip](https://github.com/maybe-hello-world/40k-roster-formatter/files/9236971/Rosters.zip)

The Necrons list should be 3 points where the program gives 5 points.
Blood Angels should be 10 points where it's listed as 13 points.
Dark Angels are 6/7.
Drukhari/Harlequins are 5/6.

**Comment by maybe-hello-world** [comment]
Thank you! I'll take a look.

**Comment by maybe-hello-world** [comment]
Regarding Necrons list: your roster includes 10 Scorpech Destroyers (3 wounds each) and 9 Tomb Blades (2 wounds each), that's 48 wounds. + 2 Plasmacytes and 5 immortals together bring us to 55 wounds => 6 points for No Prisoners.

Blood Angels: 5 voidsmen, 5 incursors, 6 assaults, 4 inceptors, 16 death company marines, 21 sanguinary guards => together 111 wounds, and it's 13 points.

I also checked calculations for Dark Angels and Drukharies.

If you open Web Developer Tools and switch to the Console tab, you can look at the debug log and check the output by yourself.

I'm closing the issue, for now, feel free to reopen it if I miscalculated something or if you found any other errors regarding this. :)
Thank you!
