### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by Arinok55** [maybe-hello-world/40k-roster-formatter#57]
I tried to upload my Eldar list and it came back with that message. It's a legal list just has a bunch of units.

**Comment by maybe-hello-world** [comment]
Thank you, it's definitely a bug.
Can you attach please your list?

**Comment by maybe-hello-world** [comment]
Thank you, it's definitely a bug.
Can you attach please your list?

**Comment by Arinok55** [comment]
I don't see a way to directly add it so I have a link to the google drive I put it in: https://drive.google.com/file/d/1pBIbnrjtBh36XAQw10JBZgdGRYmUoe2q/view?usp=sharing

**Comment by maybe-hello-world** [comment]
Fixed by #58.
BattleScribe developers again surprise me :) I believed that there exist models and units of models, but not units of units of models... 
Anyway, should be fixed now and correctly calculating secondaries.
Feel free to reopen the issue if anything.

**Comment by WH40K-TTS** [comment]
[Leonidas_Orkz.zip](https://github.com/maybe-hello-world/40k-roster-formatter/files/9946042/Leonidas_Orkz.zip)
Same error with this ork army list. "list index out of range"

**Comment by maybe-hello-world** [comment]
Fixed by #68.
Thank you for reporting, seems like I need to sit down and rewrite this stuff properly... :D
Feel free to open a new issue if anything similar occurs.
