### ISSUE TITLE
Sisters of battle supreme command detachment

### ISSUE THREAD

**Issue by CMonnin** [maybe-hello-world/40k-roster-formatter#60]
When converting a BS list with a supreme command detachment containing morvehn vahl it lists her twice which also causes errors for secondaries, and point total of the detachment

![image](https://user-images.githubusercontent.com/113541912/190210088-57819f63-0ac0-4e9d-931b-30ed74376c15.png)

**Comment by maybe-hello-world** [comment]
Thanks, I'll take a look. Definitely a bug.
