### ISSUE TITLE
Error "no such child: {http://www.battlescribe.net/schema/rosterSchema}profiles"

### ISSUE THREAD

**Issue by szymontrapp** [maybe-hello-world/40k-roster-formatter#66]
When I upload my roster that Battlescribe saved, I get an error:

`no such child: {http://www.battlescribe.net/schema/rosterSchema}profiles`

**Comment by szymontrapp** [comment]
I'm not sure how to attach my roster file.

**Comment by szymontrapp** [comment]
[Pod League October.zip](https://github.com/maybe-hello-world/40k-roster-formatter/files/9795190/Pod.League.October.zip)

**Comment by szymontrapp** [comment]
Added the roster now.

**Comment by maybe-hello-world** [comment]
Thanks, I'll check it ASAP! :)

**Comment by maybe-hello-world** [comment]
Well, as usual, the problem was in battlescribe data. I added workaround in #1cdf51ba6648654282c289af9f3c94cb54d41607, hope it would work ok.
Thank you for reporting this issue, it was pretty important.
