### ISSUE TITLE
New Arks Detachment Parse error

### ISSUE THREAD

**Issue by holsee** [maybe-hello-world/40k-roster-formatter#70]
invalid literal for int() with base 10: 'detachment'

I grabbed the files from BSData/wh40k repo for BS and noticed the formatter isn't coping with the new detachment when uploaded. 

Thanks

**Comment by maybe-hello-world** [comment]
Thank you for reporting! 
I'll check

**Comment by maybe-hello-world** [comment]
Fixed by #71
