### ISSUE TITLE
Incorrect Bring it Down Calculated

### ISSUE THREAD

**Issue by MikeEmery** [maybe-hello-world/40k-roster-formatter#72]
I'm pretty sure the bring it down calculation for this list is incorrect, it shows as 15 but it should be 18

8 ballistari - 8
6 dragoons - 6
2 duneriders - 4

Total is 18

[Mars - Copy.zip](https://github.com/maybe-hello-world/40k-roster-formatter/files/10878178/Mars.-.Copy.zip)

**Comment by maybe-hello-world** [comment]
Thanks, I'll investigate!

**Comment by maybe-hello-world** [comment]
Oh, well.
The maximum number of points for each secondary is 15, that's why it reduces it. I'll make it more transparent later.
I'm closing this ticket for now.

**Comment by MikeEmery** [comment]
Now that you explain it, makes sense.

**Comment by maybe-hello-world** [comment]
Sorry for pinging, but decided you'd probably like to know.
Removed 15-points cap and added it as an optional flag :)
